[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
caller-dummy = "CbWDKSadpzo8kFJKGZtb4VYL7uzcPrisGffYsKhCNFhP"
cpi_rollback_example = "xNyCJ1gu9qgj134fgRggGDYA6LrmyA8RzwxwfaJy5v8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
